services:
  backend:
    build: ./backend
    container_name: quick-comm-backend
    environment:
      - MONGO_URI=${MONGO_URI}  # use this to read from .env file 
    ports:
      - "4000:4000"
    

  frontend:
    build: ./frontend
    container_name: quick-comm-frontend
    ports:
      - "3000:80"



# commands to run for backend & frontend dockerfiles build
# cd ..
# docker-compose up -d

# only want to build & run Mongo for now
# docker-compose up -d mongo


# want to start Mongo and see logs
# docker-compose up mongo

# Build backend + frontend later
# docker-compose up -d backend
# docker-compose up -d frontend