services:
  backend:
    build: ./backend-scripts
    container_name: quick-comm-backend
    env_file:
      - .env
    ports:
      - "4000:4000"   # TEMP: remove later when nginx is added
    restart: always

  frontend:
    build: ./web-client/app
    container_name: quick-comm-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"   # Next.js runs on 3000
    restart: always


# commands to run for backend & frontend dockerfiles build
# cd ..
# docker-compose up -d

# only want to build & run Mongo for now
# docker-compose up -d mongo


# want to start Mongo and see logs
# docker-compose up mongo

# Build backend + frontend later
# docker-compose up -d backend
# docker-compose up -d frontend